### ISSUE TITLE
Github branches

### ISSUE THREAD

**Issue by Boodyahmedhamdy** [Boodyahmedhamdy/PasswordManager#2]
create github branches away from the `master` branch to avoid updates that can make the app crashes

**Comment by MahmoudMabrok** [comment]
I think we might name `development` as `develop`
also, it should be synced with master. 

but I think we should go to trunk based model, by creating short lived branches then merged to mastermind make another branch for release or "make master" source for release. 
and use develop as active state of app.

**Comment by Boodyahmedhamdy** [comment]
I am so happy to see you again Mr. Mahmoud. Thank you for this beautiful comment❤️


I will keep your instructions in mind and - god willing - implement them as soon as possible


Thanks again I really appreciate your advices. 
@MahmoudMabrok
